tests: Update Tests to Catch Up with App Changes
There were several changes required to bring the tests up-to-date with
changes that were made in the application. Of all the tests that are
now enabled to run, I've seen them complete at least once. However, if
you try to run the whole suite, a significant percentage of the tests
will still fail sporadically.

There are a few tests that have been identified that fail consistently:
those have been marked with ignore attributes and need to be fixed.

The main, notable changes made for catch up are as follows:

* Remove the use of the 'safe://' prefix in NRS strings.
* Small changes in the format of error messages from the safe API.
* For files based tests, contents of test data was updated and hard
  coded values for things like sizes were changed to read the test data
  dynamically.
* For files and a few other test categories, the use of the duct cmd!
  macro has been replaced in favour of the safe_cmd helper function,
  which will output stdout and stderr for failed commands.
* Wallet tests and benchmarks completely removed since commands related
  to wallets have been removed.
* Tests related to the `keypair`, `keys balance` and `keys transfer`
  have also been removed, since these commands no longer exist.

The tests have also been configured to use Color Eyre, which is useful
for more detailed error output.

diff --git a/resources/test-scripts/cli-tests b/resources/test-scripts/cli-tests
--- a/resources/test-scripts/cli-tests
+++ b/resources/test-scripts/cli-tests
@@ -1,18 +1,21 @@
 #!/bin/bash
 
-set -e -x
+# The intention of this is to exit with a non-zero status code if any of
+# the tests fail, but to allow all of them the opportunity to run, since
+# they're all independent of one another.
+exit=0
 
-function run_cli_tests() {
-    target/debug/safe keys create --test-coins --for-cli
-    cargo test --release --test cli_cat
-    cargo test --release --test cli_dog
-    cargo test --release --test cli_files -- --test-threads=1
-    cargo test --release --test cli_files_get -- --test-threads=1
-    cargo test --release --test cli_keys
-    cargo test --release --test cli_wallet
-    cargo test --release --test cli_nrs
-    cargo test --release --test cli_seq
-    cd -
-}
+export SN_CLI_QUERY_TIMEOUT=15
+export RUST_BACKTRACE=full
+declare -a exit_codes
 
-run_cli_tests
+target/release/safe keys create --test-coins --for-cli || ((exit++))
+cargo test --release --test cli_cat || ((exit++))
+cargo test --release --test cli_dog || ((exit++))
+cargo test --release --test cli_files -- --test-threads=1 || ((exit++))
+cargo test --release --test cli_files_get -- --test-threads=1 || ((exit++))
+cargo test --release --test cli_keys || ((exit++))
+cargo test --release --test cli_nrs || ((exit++))
+cargo test --release --test cli_seq || ((exit++))
+
+exit $exit
