ci: reenable churn tests on self-hosted infra
Used only in merge run to avoid overbilling in regular PRs

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -290,6 +290,84 @@ jobs:
         if: failure()
         continue-on-error: true
 
+  e2e-split:
+    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
+    name: E2E Churn test (EC2)
+    runs-on: self-hosted
+    env:
+      CARGO_HOME: /mnt/data/cargo
+      TMPDIR: /mnt/data/tmp
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: Swatinem/rust-cache@v1
+        continue-on-error: true
+        with:
+          cache-on-failure: true
+          sharedKey: ${{github.run_id}}
+
+      # This starts a NODE_COUNT node network, and then adds 12 more nodes. We should kill before moving on to split checks
+      - name: Run network churn data integrity test
+        timeout-minutes: 35 # made 35 for now due to client slowdown. TODO: fix that!
+        shell: bash
+        run: cargo run --release --example churn
+
+      - name: Build all tests before running
+        run: cargo test --no-run --release --package sn_client
+
+      - name: Ensure no nodes have left during test runs
+        timeout-minutes: 1
+        shell: bash
+        # we just want to print out the info. If there is none, an exit code of 1 is returned, so here we return true
+        run: rg "Membership - decided" $HOME/.safe/node/local-test-network | rg Left || true
+
+      - name: Are nodes still running...?
+        shell: bash
+        timeout-minutes: 1
+        continue-on-error: true
+        run: |
+          echo "$(pgrep sn_node | wc -l) nodes still running"
+          ls $HOME/.safe/node/local-test-network
+
+      - name: Kill all nodes
+        shell: bash
+        timeout-minutes: 1
+        if: failure()
+        continue-on-error: true
+        run: |
+          pkill sn_node
+          echo "$(pgrep sn_node | wc -l) nodes still running"
+
+      - name: Generate StateMap
+        shell: bash
+        if: failure()
+        continue-on-error: true
+        run: |
+          cargo install --git https://github.com/TritonDataCenter/statemap.git
+          ./resources/scripts/statemap-preprocess.sh --run-statemap > safe_statemap.svg
+
+      - name: Upload StateMap
+        uses: actions/upload-artifact@main
+        if: failure()
+        with:
+          name: statemap_e2e_split_self_hosted_ubuntu.svg
+          path: safe_statemap.svg
+        continue-on-error: true
+
+      - name: Tar log files
+        shell: bash
+        continue-on-error: true
+        run: find ~/.safe/node/local-test-network -iname '*.log*' | tar -zcvf log_files.tar.gz --files-from -
+        if: failure()
+
+      - name: Upload Node Logs
+        uses: actions/upload-artifact@main
+        with:
+          name: sn_node_logs_e2e_split_self_hosted_ubuntu
+          path: log_files.tar.gz
+        if: failure()
+        continue-on-error: true
+
   # e2e-split:
   #   #if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
   #   # disabled temporarily since `self-hosted-ubuntu` runner not available for NodeRefactorBranch branch
