ci: reenable split test

diff --git a/.github/workflows/run_pr_checks.yml b/.github/workflows/run_pr_checks.yml
--- a/.github/workflows/run_pr_checks.yml
+++ b/.github/workflows/run_pr_checks.yml
@@ -411,6 +411,10 @@ jobs:
           cache-on-failure: true
           sharedKey: ${{github.run_id}}
 
+      - name: Build sn bins
+        run: cd sn_node && cargo build --release --bins
+        timeout-minutes: 60
+
       # This starts a NODE_COUNT node network, and then adds 12 more nodes. We should kill before moving on to split checks
       - name: Run network churn data integrity test
         timeout-minutes: 55 # made 55 for now due to slow network startup
@@ -420,6 +424,144 @@ jobs:
       - name: Ensure no nodes have left during test runs
         timeout-minutes: 1
         shell: bash
+        # we just want to print out the info. If there is none, an exit code of 1 is returned, so here we return true
+        run: rg "Membership - decided" $HOME/.safe/node/local-test-network | rg Left || true
+
+      - name: Are nodes still running...?
+        shell: bash
+        timeout-minutes: 1
+        continue-on-error: true
+        run: |
+          echo "$(pgrep sn_node | wc -l) nodes still running"
+          ls $HOME/.safe/node/local-test-network
+
+      - name: Kill all nodes
+        shell: bash
+        timeout-minutes: 1
+        if: failure()
+        continue-on-error: true
+        run: |
+          pkill sn_node
+          echo "$(pgrep sn_node | wc -l) nodes still running"
+
+      - name: Generate StateMap
+        shell: bash
+        if: failure()
+        continue-on-error: true
+        run: |
+          cargo install --git https://github.com/TritonDataCenter/statemap.git
+          ./resources/scripts/statemap-preprocess.sh --run-statemap > safe_statemap.svg
+
+      - name: Upload StateMap
+        uses: actions/upload-artifact@main
+        if: failure()
+        with:
+          name: statemap_e2e_churn_self_hosted_ubuntu.svg
+          path: safe_statemap.svg
+        continue-on-error: true
+
+      - name: Tar log files
+        shell: bash
+        continue-on-error: true
+        run: find ~/.safe/node/local-test-network -iname '*.log*' | tar -zcvf log_files.tar.gz --files-from -
+        if: failure()
+
+      - name: Upload Node Logs
+        uses: actions/upload-artifact@main
+        with:
+          name: sn_node_logs_e2e_churn_self_hosted_ubuntu
+          path: log_files.tar.gz
+        if: failure()
+        continue-on-error: true
+
+
+  e2e-split:
+    #if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
+    # disabled temporarily since `self-hosted-ubuntu` runner not available for NodeRefactorBranch branch
+    if: false
+    name: E2E tests w/ full network
+    runs-on: ubuntu-latest
+    env:
+      NODE_COUNT: 15
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install Rust
+        id: toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          override: true
+
+      - uses: Swatinem/rust-cache@v1
+        continue-on-error: true
+        with:
+          cache-on-failure: true
+          sharedKey: ${{github.run_id}}
+
+      - name: install ripgrep ubuntu
+        run: sudo apt-get install ripgrep
+        if: matrix.os == 'ubuntu-latest'
+
+      # - name: install ripgrep mac
+      #   run: brew install ripgrep
+      #   if: matrix.os == 'macos-latest'
+
+      # - name: install ripgrep windows
+      #   run: choco install ripgrep
+      #   if: matrix.os == 'windows-latest'
+
+      - name: Build sn bins
+        run: cd sn_node && cargo build --release --bins
+        timeout-minutes: 60
+
+      # - name: Build testnet
+      #   run: cd testnet && cargo build  --release --bin testnet
+      #   timeout-minutes: 60
+
+      # This starts a NODE_COUNT node network, and then adds 15 _more_ nodes
+      - name: Run network split data integrity test
+        timeout-minutes: 55 # made 55 for now due to client slowdown. TODO: fix that!
+        shell: bash
+        run: cargo run --release --example network_split
+        env:
+          RUST_LOG: "sn_node,sn_client,sn_consensus,sn_dysfunction=trace"
+
+      - name: Print Network Log Stats at start
+        shell: bash
+        run: ./target/release/log_cmds_inspector $HOME/.safe/node/local-test-network
+
+      - name: Wait for all nodes to join
+        shell: bash
+        # we should not have the full 33 nodes as yet.
+        run: NODE_COUNT=28 ./resources/scripts/wait_for_nodes_to_join.sh
+        timeout-minutes: 20
+
+      - name: Is the network split and ready?
+        shell: bash
+        run: ./resources/scripts/network_is_ready.sh
+        timeout-minutes: 5
+
+      - name: Build all tests before running
+        run: cd sn_client && cargo test --no-run --release -p sn_client
+        timeout-minutes: 50
+
+      - name: Run client tests
+        env:
+          RUST_LOG: "sn_client=trace,qp2p=debug"
+        run: cargo test --release -p sn_client -- --test-threads=1
+        timeout-minutes: 25
+
+      - name: Run example app for file API against local network
+        timeout-minutes: 10
+        shell: bash
+        run: cargo run --release --example client_files
+
+      - name: Ensure no nodes have left during test runs
+        timeout-minutes: 1
+        shell: bash
+        if: matrix.os != 'windows-latest'
         # we just want to print out the info. If there is none, an exit code of 1 is returned, so here we return true
         run: rg "Membership - decided" $HOME/.safe/node/local-test-network | rg Left || true
 
@@ -469,6 +611,14 @@ jobs:
           path: log_files.tar.gz
         if: failure()
         continue-on-error: true
+
+     # if we don't clean up, the .safe folder might persist between runs
+      - name: Cleanup self-hosted runner
+        if: always()
+        run: |
+          killall -9 sn_node
+          sleep 10
+          rm -rf ~/.safe
 
   api:
     if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
