use CI just for testing membership

diff --git a/.github/workflows/sn_pr_tests.yml b/.github/workflows/sn_pr_tests.yml
--- a/.github/workflows/sn_pr_tests.yml
+++ b/.github/workflows/sn_pr_tests.yml
@@ -30,7 +30,7 @@ jobs:
       - api
       - cli
       # - e2e-split
-      - unit
+      # - unit
       - checks
       - lint
     runs-on: ubuntu-latest
@@ -109,61 +109,61 @@ jobs:
         # See https://doc.rust-lang.org/rustdoc/lints.html for lints that are 'warning' by default.
         run: RUSTDOCFLAGS="--deny=warnings" cargo doc --no-deps
 
-  unit:
-    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
-    name: Unit Tests
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
-    steps:
-      - uses: actions/checkout@v2
+  # unit:
+  #   if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
+  #   name: Unit Tests
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest, windows-latest, macos-latest]
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Install Rust
-        id: toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          profile: minimal
-          toolchain: stable
-          override: true
+  #     - name: Install Rust
+  #       id: toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         profile: minimal
+  #         toolchain: stable
+  #         override: true
 
-      - uses: Swatinem/rust-cache@v1
-        continue-on-error: true
-        with:
-          cache-on-failure: true
-          sharedKey: ${{github.run_id}}-unit
+  #     - uses: Swatinem/rust-cache@v1
+  #       continue-on-error: true
+  #       with:
+  #         cache-on-failure: true
+  #         sharedKey: ${{github.run_id}}-unit
 
-      - name: Build sn_interface tests before running
-        run: cd sn_interface && cargo test --no-run --release
-        timeout-minutes: 50
+  #     - name: Build sn_interface tests before running
+  #       run: cd sn_interface && cargo test --no-run --release
+  #       timeout-minutes: 50
 
-      - name: Run sn_interface tests
-        timeout-minutes: 25
-        run: cd sn_interface && cargo test --release
+  #     - name: Run sn_interface tests
+  #       timeout-minutes: 25
+  #       run: cd sn_interface && cargo test --release
 
-      - name: Build sn_dysfunction tests before running
-        run: cd sn_dysfunction && cargo test --no-run --release
-        timeout-minutes: 50
+  #     - name: Build sn_dysfunction tests before running
+  #       run: cd sn_dysfunction && cargo test --no-run --release
+  #       timeout-minutes: 50
 
-      - name: Run sn_dysfunction tests
-        timeout-minutes: 15
-        run: cd sn_dysfunction && cargo test --release
+  #     - name: Run sn_dysfunction tests
+  #       timeout-minutes: 15
+  #       run: cd sn_dysfunction && cargo test --release
 
-      - name: Build sn_node tests before running
-        run: cd sn_node && cargo test --no-run --release
-        timeout-minutes: 50
+  #     - name: Build sn_node tests before running
+  #       run: cd sn_node && cargo test --no-run --release
+  #       timeout-minutes: 50
 
-      - name: Run sn_node tests
-        timeout-minutes: 20
-        run: cd sn_node && cargo test --release
+  #     - name: Run sn_node tests
+  #       timeout-minutes: 20
+  #       run: cd sn_node && cargo test --release
 
-      - name: Build sn_cli tests before running
-        run: cd sn_cli && cargo test --no-run --release
-        timeout-minutes: 50
+  #     - name: Build sn_cli tests before running
+  #       run: cd sn_cli && cargo test --no-run --release
+  #       timeout-minutes: 50
 
-      - name: Run sn_cli tests
-        timeout-minutes: 25
-        run: cd sn_cli && cargo test --release --bin safe
+  #     - name: Run sn_cli tests
+  #       timeout-minutes: 25
+  #       run: cd sn_cli && cargo test --release --bin safe
 
   e2e:
     if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
@@ -225,20 +225,139 @@ jobs:
         run: ./resources/scripts/wait_for_nodes_to_join.sh
         timeout-minutes: 5
 
-      - name: Build all tests before running non ubuntu
-        run: cd sn_client && cargo test --no-run --release
-        timeout-minutes: 50
+      # - name: Build all tests before running non ubuntu
+      #   run: cd sn_client && cargo test --no-run --release
+      #   timeout-minutes: 50
 
-      - name: Run client tests
-        env:
-          RUST_LOG: "sn_client=trace,qp2p=debug"
-        run: cd sn_client && cargo test --release -- --test-threads=1
-        timeout-minutes: 50
+      # - name: Run client tests
+      #   env:
+      #     RUST_LOG: "sn_client=trace,qp2p=debug"
+      #   run: cd sn_client && cargo test --release -- --test-threads=1
+      #   timeout-minutes: 50
 
-      - name: Run example app for file API against local network
-        timeout-minutes: 10
+      # - name: Run example app for file API against local network
+      #   timeout-minutes: 10
+      #   shell: bash
+      #   run: cd sn_client && cargo run --release --example client_files
+
+      - name: Ensure no nodes have left during test runs
+        timeout-minutes: 1
         shell: bash
-        run: cd sn_client && cargo run --release --example client_files
+        if: matrix.os != 'windows-latest'
+        # we just want to print out the info. If there is none, an exit code of 1 is returned, so here we return true
+        run: rg "Membership - decided" $HOME/.safe/node/local-test-network | rg Left || true
+
+      - name: Are nodes still running...?
+        shell: bash
+        timeout-minutes: 1
+        if: failure() && matrix.os != 'windows-latest'
+        continue-on-error: true
+        run: |
+          echo "$(pgrep sn_node | wc -l) nodes still running"
+          ls $HOME/.safe/node/local-test-network
+
+      - name: Generate StateMap
+        shell: bash
+        continue-on-error: true
+        run: |
+          cargo install --git https://github.com/TritonDataCenter/statemap.git
+          ./resources/scripts/statemap-preprocess.sh --run-statemap > safe_statemap.svg
+
+      - name: Upload StateMap
+        uses: actions/upload-artifact@main
+        with:
+          name: statemap_e2e_${{matrix.os}}.svg
+          path: safe_statemap.svg
+        continue-on-error: true
+
+      - name: Tar log files
+        shell: bash
+        continue-on-error: true
+        run: find ~/.safe/node/local-test-network -iname '*.log*' | tar -zcvf log_files.tar.gz --files-from -
+        if: failure()
+
+      - name: Upload Node Logs
+        uses: actions/upload-artifact@main
+        with:
+          name: sn_node_logs_e2e_${{matrix.os}}
+          path: log_files.tar.gz
+        if: failure()
+        continue-on-error: true
+
+  bonus-runs:
+    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
+    name: E2E tests bonus
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install Rust
+        id: toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          override: true
+
+      - uses: Swatinem/rust-cache@v1
+        continue-on-error: true
+        with:
+          cache-on-failure: true
+          sharedKey: ${{github.run_id}}
+
+      - name: install ripgrep ubuntu
+        run: sudo apt-get install ripgrep
+        if: matrix.os == 'ubuntu-latest'
+
+      - name: install ripgrep mac
+        run: brew install ripgrep
+        if: matrix.os == 'macos-latest'
+
+      - name: install ripgrep windows
+        run: choco install ripgrep
+        if: matrix.os == 'windows-latest'
+
+      - name: Build sn bins
+        run: cd sn_node && cargo build --release --bins
+        timeout-minutes: 60
+
+      - name: Build testnet
+        run: cd testnet && cargo build --release --bin testnet
+        timeout-minutes: 60
+
+      # - name: Build log_cmds_inspector
+      #   run: cargo build  --release --bin log_cmds_inspector
+      #   timeout-minutes: 60
+
+      - name: Start the network
+        run: ./target/release/testnet --interval 30000
+        id: section-startup
+        env:
+          RUST_LOG: "sn_node,sn_consensus,sn_dysfunction=trace,sn_interface=trace"
+
+      - name: Wait for all nodes to join
+        shell: bash
+        run: ./resources/scripts/wait_for_nodes_to_join.sh
+        timeout-minutes: 5
+
+      # - name: Build all tests before running non ubuntu
+      #   run: cd sn_client && cargo test --no-run --release
+      #   timeout-minutes: 50
+
+      # - name: Run client tests
+      #   env:
+      #     RUST_LOG: "sn_client=trace,qp2p=debug"
+      #   run: cd sn_client && cargo test --release -- --test-threads=1
+      #   timeout-minutes: 50
+
+      # - name: Run example app for file API against local network
+      #   timeout-minutes: 10
+      #   shell: bash
+      #   run: cd sn_client && cargo run --release --example client_files
 
       - name: Ensure no nodes have left during test runs
         timeout-minutes: 1
@@ -508,23 +627,23 @@ jobs:
         run: ./resources/scripts/wait_for_nodes_to_join.sh
         timeout-minutes: 5
 
-      - name: Build all tests before running
-        run: cd sn_api && cargo test --no-run --release
-        timeout-minutes: 50
+      # - name: Build all tests before running
+      #   run: cd sn_api && cargo test --no-run --release
+      #   timeout-minutes: 50
 
-      - name: Run API tests
-        env:
-          RUST_LOG: "sn_client=trace"
-        run: cd sn_api && cargo test --release -- --test-threads=1
-        timeout-minutes: 30
+      # - name: Run API tests
+      #   env:
+      #     RUST_LOG: "sn_client=trace"
+      #   run: cd sn_api && cargo test --release -- --test-threads=1
+      #   timeout-minutes: 30
 
-      - name: Are nodes still running...?
-        shell: bash
-        timeout-minutes: 1
-        if: failure() && matrix.os
-        run: |
-          echo "$(pgrep sn_node | wc -l) nodes still running"
-          ls $HOME/.safe/node/local-test-network
+      # - name: Are nodes still running...?
+      #   shell: bash
+      #   timeout-minutes: 1
+      #   if: failure() && matrix.os
+      #   run: |
+      #     echo "$(pgrep sn_node | wc -l) nodes still running"
+      #     ls $HOME/.safe/node/local-test-network
 
       - name: Ensure no nodes have left during test runs
         timeout-minutes: 1
@@ -617,24 +736,24 @@ jobs:
         run: ./resources/scripts/wait_for_nodes_to_join.sh
         timeout-minutes: 5
 
-      - name: Generate keys for test run
-        run: cargo run --package sn_cli --release -- keys create --for-cli
+      # - name: Generate keys for test run
+      #   run: cargo run --package sn_cli --release -- keys create --for-cli
 
-      - name: Build all tests before running
-        run: cd sn_cli && cargo test --no-run --release
-        timeout-minutes: 50
+      # - name: Build all tests before running
+      #   run: cd sn_cli && cargo test --no-run --release
+      #   timeout-minutes: 50
 
-      - name: Run CLI tests
-        run: cd sn_cli && cargo test --release -- --test-threads=1
-        timeout-minutes: 50
+      # - name: Run CLI tests
+      #   run: cd sn_cli && cargo test --release -- --test-threads=1
+      #   timeout-minutes: 50
 
-      - name: Are nodes still running...?
-        shell: bash
-        timeout-minutes: 1
-        if: failure() && matrix.os
-        run: |
-          echo "$(pgrep sn_node | wc -l) nodes still running"
-          ls $HOME/.safe/node/local-test-network
+      # - name: Are nodes still running...?
+      #   shell: bash
+      #   timeout-minutes: 1
+      #   if: failure() && matrix.os
+      #   run: |
+      #     echo "$(pgrep sn_node | wc -l) nodes still running"
+      #     ls $HOME/.safe/node/local-test-network
 
       - name: Ensure no nodes have left during test runs
         timeout-minutes: 1
