ci: reenable cli tests

diff --git a/.github/workflows/sn_pr_tests.yml b/.github/workflows/sn_pr_tests.yml
--- a/.github/workflows/sn_pr_tests.yml
+++ b/.github/workflows/sn_pr_tests.yml
@@ -27,11 +27,12 @@ jobs:
       - cargo-udeps
       - cargo-deny
       - e2e
+      - api
+      - cli
       # - e2e-split
       - unit
       - checks
       - lint
-      # - upload_event_file
     runs-on: ubuntu-latest
     steps:
       - name: CI succeeded
@@ -560,130 +561,114 @@ jobs:
         if: failure()
         continue-on-error: true
 
-  # cli:
-  #   if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
-  #   name: Run CLI tests
-  #   runs-on: ${{ matrix.os }}
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       os: [ubuntu-latest, windows-latest, macos-latest]
-  #   steps:
-  #     - uses: actions/checkout@v2
+  cli:
+    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
+    name: Run CLI tests
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+    steps:
+      - uses: actions/checkout@v2
 
-  #     - name: Install Rust
-  #       id: toolchain
-  #       uses: actions-rs/toolchain@v1
-  #       with:
-  #         profile: minimal
-  #         toolchain: stable
-  #         override: true
+      - name: Install Rust
+        id: toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: stable
+          override: true
 
-  #     - uses: Swatinem/rust-cache@v1
-  #       continue-on-error: true
-  #       with:
-  #         cache-on-failure: true
-  #         sharedKey: ${{github.run_id}}
+      - uses: Swatinem/rust-cache@v1
+        continue-on-error: true
+        with:
+          cache-on-failure: true
+          sharedKey: ${{github.run_id}}
 
-  #     - name: install ripgrep ubuntu
-  #       run: sudo apt-get install ripgrep
-  #       if: matrix.os == 'ubuntu-latest'
+      - name: install ripgrep ubuntu
+        run: sudo apt-get install ripgrep
+        if: matrix.os == 'ubuntu-latest'
 
-  #     - name: install ripgrep mac
-  #       run: brew install ripgrep
-  #       if: matrix.os == 'macos-latest'
+      - name: install ripgrep mac
+        run: brew install ripgrep
+        if: matrix.os == 'macos-latest'
 
-  #     - name: install ripgrep windows
-  #       run: choco install ripgrep
-  #       if: matrix.os == 'windows-latest'
+      - name: install ripgrep windows
+        run: choco install ripgrep
+        if: matrix.os == 'windows-latest'
 
-  #     - name: Build sn bins
-  #       run: cd sn_node && cargo build --release --bins
-  #       timeout-minutes: 60
+      - name: Build sn bins
+        run: cd sn_node && cargo build --release --bins
+        timeout-minutes: 60
 
-  #     - name: Build testnet
-  #       run: cd testnet && cargo build  --release --bin testnet
-  #       timeout-minutes: 60
+      - name: Build testnet
+        run: cd testnet && cargo build  --release --bin testnet
+        timeout-minutes: 60
 
-  #     - name: Start the network
-  #       run: ./target/release/testnet --interval 30000
-  #       id: section-startup
-  #       env:
-  #         RUST_LOG: "sn_node,sn_api,sn_consensus,sn_dysfunction=trace,sn_interface=trace"
+      - name: Start the network
+        run: ./target/release/testnet --interval 30000
+        id: section-startup
+        env:
+          RUST_LOG: "sn_node,sn_api,sn_consensus,sn_dysfunction=trace,sn_interface=trace"
 
-  #     - name: Wait for all nodes to join
-  #       shell: bash
-  #       run: ./resources/scripts/wait_for_nodes_to_join.sh
-  #       timeout-minutes: 5
+      - name: Wait for all nodes to join
+        shell: bash
+        run: ./resources/scripts/wait_for_nodes_to_join.sh
+        timeout-minutes: 5
 
-  #     - name: Generate keys for test run
-  #       run: cargo run --package sn_cli --release -- keys create --for-cli
+      - name: Generate keys for test run
+        run: cargo run --package sn_cli --release -- keys create --for-cli
 
-  #     - name: Build all tests before running
-  #       run: cd sn_cli && cargo test --no-run --release
-  #       timeout-minutes: 50
+      - name: Build all tests before running
+        run: cd sn_cli && cargo test --no-run --release
+        timeout-minutes: 50
 
-  #     - name: Run CLI tests
-  #       run: cd sn_cli && cargo test --release
-  #       env:
-  #         RUST_LOG: "sn_client=trace"
-  #       timeout-minutes: 50
+      - name: Run CLI tests
+        run: cd sn_cli && cargo test --release -- --test-threads=1
+        env:
+          RUST_LOG: "sn_client=trace"
+        timeout-minutes: 50
 
-  #     - name: Are nodes still running...?
-  #       shell: bash
-  #       timeout-minutes: 1
-  #       if: failure() && matrix.os
-  #       run: |
-  #         echo "$(pgrep sn_node | wc -l) nodes still running"
-  #         ls $HOME/.safe/node/local-test-network
+      - name: Are nodes still running...?
+        shell: bash
+        timeout-minutes: 1
+        if: failure() && matrix.os
+        run: |
+          echo "$(pgrep sn_node | wc -l) nodes still running"
+          ls $HOME/.safe/node/local-test-network
 
-  #     - name: Ensure no nodes have left during test runs
-  #       timeout-minutes: 1
-  #       shell: bash
-  #       if: matrix.os != 'windows-latest'
-  #       # we just want to print out the info. If there is none, an exit code of 1 is returned, so here we return true
-  #       run: rg "Membership - decided" $HOME/.safe/node/local-test-network | rg Left || true
+      - name: Ensure no nodes have left during test runs
+        timeout-minutes: 1
+        shell: bash
+        if: matrix.os != 'windows-latest'
+        # we just want to print out the info. If there is none, an exit code of 1 is returned, so here we return true
+        run: rg "Membership - decided" $HOME/.safe/node/local-test-network | rg Left || true
 
-  #     - name: Generate StateMap
-  #       shell: bash
-  #       continue-on-error: true
-  #       run: |
-  #         cargo install --git https://github.com/TritonDataCenter/statemap.git
-  #         ./resources/scripts/statemap-preprocess.sh --run-statemap > safe_statemap.svg
+      - name: Generate StateMap
+        shell: bash
+        continue-on-error: true
+        run: |
+          cargo install --git https://github.com/TritonDataCenter/statemap.git
+          ./resources/scripts/statemap-preprocess.sh --run-statemap > safe_statemap.svg
 
-  #     - name: Upload StateMap
-  #       uses: actions/upload-artifact@main
-  #       with:
-  #         name: statemap_cli_${{matrix.os}}.svg
-  #         path: safe_statemap.svg
-  #       continue-on-error: true
+      - name: Upload StateMap
+        uses: actions/upload-artifact@main
+        with:
+          name: statemap_cli_${{matrix.os}}.svg
+          path: safe_statemap.svg
+        continue-on-error: true
 
-  #     - name: Tar log files
-  #       shell: bash
-  #       continue-on-error: true
-  #       run: find ~/.safe/node/local-test-network -iname '*.log*' | tar -zcvf log_files.tar.gz --files-from -
-  #       if: failure()
+      - name: Tar log files
+        shell: bash
+        continue-on-error: true
+        run: find ~/.safe/node/local-test-network -iname '*.log*' | tar -zcvf log_files.tar.gz --files-from -
+        if: failure()
 
-  #     - name: Upload Node Logs
-  #       uses: actions/upload-artifact@main
-  #       with:
-  #         name: sn_node_logs_cli_${{matrix.os}}
-  #         path: log_files.tar.gz
-  #       if: failure()
-  #       continue-on-error: true
-
-  # This is required for publishing test results that come from forks. The actual publishing of the
-  # results occurs in another workflow that will be triggered when this one finishes. Uploading this
-  # 'event file' is necessary for the triggering to occur.
-  # upload_event_file:
-  #   if: always()
-  #   name: Upload event file
-  #   needs: [unit, e2e, api, cli]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #     - name: Upload event file
-  #       uses: actions/upload-artifact@main
-  #       with:
-  #         name: event-file
-  #         path: ${{ github.event_path }}
+      - name: Upload Node Logs
+        uses: actions/upload-artifact@main
+        with:
+          name: sn_node_logs_cli_${{matrix.os}}
+          path: log_files.tar.gz
+        if: failure()
+        continue-on-error: true
